const data = [
  {
    name: "John",
    email: "john@example.com",
    contact: "941600102",
    region: "Adelanto, California",
    accepted: true,
    invited: false,
    designation: "",
    hasSeat: "",
    resetPassword: "",
    registrations: "95",
  },
  {
    name: "John",
    email: "john@example.com",
    contact: "941600102",
    region: "Adelanto, California",
    accepted: false,
    invited: true,
    designation: "",
    hasSeat: "",
    resetPassword: "",
    registrations: "95",
  },
  {
    name: "John",
    email: "john@example.com",
    contact: "941600102",
    region: "Adelanto, California",
    accepted: true,
    invited: true,
    designation: "",
    hasSeat: "",
    resetPassword: "",
    registrations: "95",
  },
  {
    name: "John",
    email: "john@example.com",
    contact: "941600102",
    region: "Adelanto, California",
    accepted: false,
    invited: true,
    designation: "",
    hasSeat: "",
    resetPassword: "",
    registrations: "95",
  },
];

export default data;
